// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "cabins",
    columns: [
      { name: "name", type: "string" },
      { name: "max_capacity", type: "int" },
      { name: "price", type: "int" },
      { name: "discount_price", type: "int" },
      { name: "description", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Cabins = InferredTypes["cabins"];
export type CabinsRecord = Cabins & XataRecord;

export type DatabaseSchema = {
  cabins: CabinsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Sergio-s-workspace-j88unm.us-east-1.xata.sh/db/the-wild-oasis",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
