import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

export default defineConfig({
    resolve: {
        alias: {
            '@': fileURLToPath(new URL('./', import.meta.url)),
        },
    },
    test: {
        coverage: {
            provider: 'v8',
            reporter: ['text', 'lcov'],
            reportsDirectory: './coverage',
            include: ['app/**', 'components/**', 'features/**', 'hooks/**', 'lib/**', 'convex/**'],
            exclude: [
                '**/_generated/**',
                '**/*.test.{ts,tsx}',
                '**/*.config.{ts,mjs}',
                // Generated by `bun run auth:generate`.
                'convex/betterAuth/schema.ts',
                // Declaration-only wiring: a single factory call or re-export with no
                // branches to cover. Exercised by the build and the e2e smoke tests;
                // a unit test here would assert that an assignment happened.
                // Anything that grows a conditional must come off this list.
                'app/layout.tsx',
                'app/api/**',
                'components/convex-client-provider.tsx',
                'convex/http.ts',
                'convex/betterAuth/auth.ts',
                'convex/betterAuth/adapter.ts',
                'lib/auth-client.ts',
                'lib/auth-server.ts',
                'lib/env.ts',
            ],
            thresholds: {
                // Global floor. Raise it as real code lands; never lower it to merge a
                // change — that inverts the tool. Read the report for uncovered error
                // and authorization paths rather than chasing the percentage.
                statements: 80,
                branches: 80,
                functions: 75,
                lines: 80,
                // Risk-bearing code carries a higher floor: every Convex function is a
                // public network surface and the place authorization is enforced.
                'convex/**': {
                    statements: 90,
                    branches: 90,
                    functions: 90,
                    lines: 90,
                },
            },
        },
        projects: [
            {
                // Convex functions run against an in-memory backend in the
                // edge runtime, matching the real Convex JS environment.
                extends: true,
                test: {
                    name: 'convex',
                    include: ['convex/**/*.test.{ts,tsx}'],
                    environment: 'edge-runtime',
                    server: { deps: { inline: ['convex-test'] } },
                },
            },
            {
                extends: true,
                plugins: [react()],
                test: {
                    name: 'frontend',
                    include: ['{app,components,features,hooks,lib}/**/*.test.{ts,tsx}'],
                    environment: 'jsdom',
                    setupFiles: ['./vitest.setup.ts'],
                    globals: true,
                },
            },
        ],
    },
});
