import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import { loadEnv } from 'vite';
import { defineConfig } from 'vitest/config';

// Vitest doesn't load `.env.local` the way `next dev`/`next build` do, so
// anything importing `lib/env.ts` (e.g. via `lib/site-config.ts`) would fail
// `@t3-oss/env-nextjs` validation as soon as a test imports it. Load it the
// same way Next does, into `process.env`, so tests see the real values.
Object.assign(process.env, loadEnv('test', process.cwd(), ''));

export default defineConfig({
    resolve: {
        alias: {
            '@': fileURLToPath(new URL('./', import.meta.url)),
        },
    },
    test: {
        coverage: {
            provider: 'v8',
            reporter: ['text', 'lcov'],
            reportsDirectory: './coverage',
            include: [
                'app/**',
                'components/**',
                'emails/**',
                'features/**',
                'hooks/**',
                'lib/**',
                'providers/**',
                'convex/**',
            ],
            exclude: [
                '**/_generated/**',
                '**/*.test.{ts,tsx}',
                '**/*.config.{ts,mjs}',
                // Generated by `bun run auth:generate`.
                'convex/betterAuth/schema.ts',
                // Declaration-only wiring: a single factory call or re-export with no
                // branches to cover. Exercised by the build and the e2e smoke tests;
                // a unit test here would assert that an assignment happened.
                // Anything that grows a conditional must come off this list.
                'app/layout.tsx',
                // Every route file is the same shape: thin, renders a screen component
                // from a feature slice (docs/02_CODING_GUIDELINES.md's own convention) or
                // gates on an auth check that's proven behaviorally by the e2e auth
                // fixture (e2e/guest-flow.spec.ts, e2e/admin-flow.spec.ts), never unit-
                // tested against Next's redirect()/notFound() internals. Same reasoning
                // as app/layout.tsx above, just applied consistently as the app grew.
                'app/**/page.tsx',
                'app/**/layout.tsx',
                // No global styles/theme reach this document (see the file's own
                // comment) -- inline-styled, no conditionals worth unit testing.
                'app/global-error.tsx',
                'app/api/**',
                'providers/convex-client-provider.tsx',
                'convex/http.ts',
                'convex/betterAuth/auth.ts',
                'convex/betterAuth/adapter.ts',
                'lib/auth-client.ts',
                'lib/auth-server.ts',
                'lib/env.ts',
                // Thin validator+delegate wrappers (docs/01/02's Convex "model pattern") --
                // all business logic lives in, and is tested via, the corresponding
                // convex/model/*.ts file directly (never through this public API surface,
                // per this project's established convex-test pattern of calling model
                // functions with `t.run()`). Nothing here has a branch of its own.
                'convex/appSettings.ts',
                'convex/availabilityBlocks.ts',
                'convex/featureFlags.ts',
                'convex/messages.ts',
                'convex/subscribers.ts',
                'convex/users.ts',
                // Internal design-system reference (see BRAND route's own doc comment:
                // "never linked from public nav") -- not part of the product surface.
                'features/brand/**',
                // shadcn-owned vendor primitives (components/ui is shadcn-owned per
                // CLAUDE.md) -- exercised indirectly through every feature test that
                // renders one; a direct unit test here would just re-assert Base UI's own
                // behavior.
                'components/ui/**',
                // Static, no-branch presentational content -- copy and links, nothing to
                // unit-test beyond what a snapshot would (guidelines: avoid large
                // snapshots, they fail on every change and get regenerated unread).
                'features/home/components/*-section.tsx',
                'features/layout/footer.tsx',
                'features/layout/admin-sidebar.tsx',
                'hooks/**',
            ],
            thresholds: {
                // Global floor. Raise it as real code lands; never lower it to merge a
                // change — that inverts the tool. Read the report for uncovered error
                // and authorization paths rather than chasing the percentage.
                statements: 80,
                branches: 80,
                functions: 75,
                lines: 80,
                // Risk-bearing code carries a higher floor: every Convex function is a
                // public network surface and the place authorization is enforced.
                'convex/**': {
                    statements: 90,
                    branches: 90,
                    functions: 90,
                    lines: 90,
                },
            },
        },
        projects: [
            {
                // Convex functions run against an in-memory backend in the
                // edge runtime, matching the real Convex JS environment.
                extends: true,
                test: {
                    name: 'convex',
                    include: ['convex/**/*.test.{ts,tsx}'],
                    environment: 'edge-runtime',
                    server: { deps: { inline: ['convex-test'] } },
                },
            },
            {
                extends: true,
                plugins: [react()],
                test: {
                    name: 'frontend',
                    include: [
                        '{app,components,emails,features,hooks,lib,providers}/**/*.test.{ts,tsx}',
                    ],
                    environment: 'jsdom',
                    setupFiles: ['./vitest.setup.ts'],
                    globals: true,
                },
            },
        ],
    },
});
