import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';

import { cn } from './_lib/utils';
import { ConvexClientProvider } from './_providers/convex-provider';
import './globals.css';

const josefineSans = Josefin_Sans({
	variable: '--font-josefin-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: {
		template: '%s | The Wild Oasis',
		default: 'The Wild Oasis',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn('antialiased', josefineSans.variable)}>
				<ConvexClientProvider>{children}</ConvexClientProvider>
			</body>
		</html>
	);
}
