/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as webIndexRouteImport } from './routes/(web)/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminCabinsRouteImport } from './routes/admin/cabins'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as webTermsRouteImport } from './routes/(web)/terms'
import { Route as webPrivacyRouteImport } from './routes/(web)/privacy'
import { Route as webGuestRouteImport } from './routes/(web)/guest'
import { Route as webContactRouteImport } from './routes/(web)/contact'
import { Route as webCabinsRouteImport } from './routes/(web)/cabins'
import { Route as webAboutRouteImport } from './routes/(web)/about'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as webCabinsIndexRouteImport } from './routes/(web)/cabins.index'
import { Route as webCabinsCabinIdRouteImport } from './routes/(web)/cabins.$cabinId'

const webIndexRoute = webIndexRouteImport.update({
  id: '/(web)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCabinsRoute = AdminCabinsRouteImport.update({
  id: '/admin/cabins',
  path: '/admin/cabins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const webTermsRoute = webTermsRouteImport.update({
  id: '/(web)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const webPrivacyRoute = webPrivacyRouteImport.update({
  id: '/(web)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const webGuestRoute = webGuestRouteImport.update({
  id: '/(web)/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const webContactRoute = webContactRouteImport.update({
  id: '/(web)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const webCabinsRoute = webCabinsRouteImport.update({
  id: '/(web)/cabins',
  path: '/cabins',
  getParentRoute: () => rootRouteImport,
} as any)
const webAboutRoute = webAboutRouteImport.update({
  id: '/(web)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const webCabinsIndexRoute = webCabinsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => webCabinsRoute,
} as any)
const webCabinsCabinIdRoute = webCabinsCabinIdRouteImport.update({
  id: '/$cabinId',
  path: '/$cabinId',
  getParentRoute: () => webCabinsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/about': typeof webAboutRoute
  '/cabins': typeof webCabinsRouteWithChildren
  '/contact': typeof webContactRoute
  '/guest': typeof webGuestRoute
  '/privacy': typeof webPrivacyRoute
  '/terms': typeof webTermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cabins': typeof AdminCabinsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof webIndexRoute
  '/cabins/$cabinId': typeof webCabinsCabinIdRoute
  '/cabins/': typeof webCabinsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/about': typeof webAboutRoute
  '/contact': typeof webContactRoute
  '/guest': typeof webGuestRoute
  '/privacy': typeof webPrivacyRoute
  '/terms': typeof webTermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cabins': typeof AdminCabinsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof webIndexRoute
  '/cabins/$cabinId': typeof webCabinsCabinIdRoute
  '/cabins': typeof webCabinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(web)/about': typeof webAboutRoute
  '/(web)/cabins': typeof webCabinsRouteWithChildren
  '/(web)/contact': typeof webContactRoute
  '/(web)/guest': typeof webGuestRoute
  '/(web)/privacy': typeof webPrivacyRoute
  '/(web)/terms': typeof webTermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cabins': typeof AdminCabinsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/(web)/': typeof webIndexRoute
  '/(web)/cabins/$cabinId': typeof webCabinsCabinIdRoute
  '/(web)/cabins/': typeof webCabinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/cabins'
    | '/contact'
    | '/guest'
    | '/privacy'
    | '/terms'
    | '/admin/bookings'
    | '/admin/cabins'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/users'
    | '/'
    | '/cabins/$cabinId'
    | '/cabins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/contact'
    | '/guest'
    | '/privacy'
    | '/terms'
    | '/admin/bookings'
    | '/admin/cabins'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/users'
    | '/'
    | '/cabins/$cabinId'
    | '/cabins'
  id:
    | '__root__'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(web)/about'
    | '/(web)/cabins'
    | '/(web)/contact'
    | '/(web)/guest'
    | '/(web)/privacy'
    | '/(web)/terms'
    | '/admin/bookings'
    | '/admin/cabins'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/users'
    | '/(web)/'
    | '/(web)/cabins/$cabinId'
    | '/(web)/cabins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  webAboutRoute: typeof webAboutRoute
  webCabinsRoute: typeof webCabinsRouteWithChildren
  webContactRoute: typeof webContactRoute
  webGuestRoute: typeof webGuestRoute
  webPrivacyRoute: typeof webPrivacyRoute
  webTermsRoute: typeof webTermsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCabinsRoute: typeof AdminCabinsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  webIndexRoute: typeof webIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(web)/': {
      id: '/(web)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof webIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cabins': {
      id: '/admin/cabins'
      path: '/admin/cabins'
      fullPath: '/admin/cabins'
      preLoaderRoute: typeof AdminCabinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/terms': {
      id: '/(web)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof webTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/privacy': {
      id: '/(web)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof webPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/guest': {
      id: '/(web)/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof webGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/contact': {
      id: '/(web)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof webContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/cabins': {
      id: '/(web)/cabins'
      path: '/cabins'
      fullPath: '/cabins'
      preLoaderRoute: typeof webCabinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/about': {
      id: '/(web)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof webAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/cabins/': {
      id: '/(web)/cabins/'
      path: '/'
      fullPath: '/cabins/'
      preLoaderRoute: typeof webCabinsIndexRouteImport
      parentRoute: typeof webCabinsRoute
    }
    '/(web)/cabins/$cabinId': {
      id: '/(web)/cabins/$cabinId'
      path: '/$cabinId'
      fullPath: '/cabins/$cabinId'
      preLoaderRoute: typeof webCabinsCabinIdRouteImport
      parentRoute: typeof webCabinsRoute
    }
  }
}

interface webCabinsRouteChildren {
  webCabinsCabinIdRoute: typeof webCabinsCabinIdRoute
  webCabinsIndexRoute: typeof webCabinsIndexRoute
}

const webCabinsRouteChildren: webCabinsRouteChildren = {
  webCabinsCabinIdRoute: webCabinsCabinIdRoute,
  webCabinsIndexRoute: webCabinsIndexRoute,
}

const webCabinsRouteWithChildren = webCabinsRoute._addFileChildren(
  webCabinsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  webAboutRoute: webAboutRoute,
  webCabinsRoute: webCabinsRouteWithChildren,
  webContactRoute: webContactRoute,
  webGuestRoute: webGuestRoute,
  webPrivacyRoute: webPrivacyRoute,
  webTermsRoute: webTermsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCabinsRoute: AdminCabinsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminUsersRoute: AdminUsersRoute,
  webIndexRoute: webIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
