import {
	PUBLIC_BOOKING_CLEANING_FEE,
	PUBLIC_BOOKING_FEE_PERCENTAGE,
	PUBLIC_BOOKING_MAX_GUESTS,
	PUBLIC_BOOKING_MAX_NIGHTS,
	PUBLIC_BOOKING_MIN_NIGHTS,
	PUBLIC_BOOKING_PROCESSING_FEE_PERCENTAGE,
	PUBLIC_BOOKING_SERVICE_FEE_PERCENTAGE,
	PUBLIC_BOOKING_TAX_RATE
} from '$env/static/public';

export const bookingConfig = {
	taxRate: Number(PUBLIC_BOOKING_TAX_RATE),
	bookingFeePercentage: Number(PUBLIC_BOOKING_FEE_PERCENTAGE),
	processingFeePercentage: Number(PUBLIC_BOOKING_PROCESSING_FEE_PERCENTAGE),
	cleaningFee: Number(PUBLIC_BOOKING_CLEANING_FEE),
	serviceFeePercentage: Number(PUBLIC_BOOKING_SERVICE_FEE_PERCENTAGE),
	maxGuests: Number(PUBLIC_BOOKING_MAX_GUESTS),
	maxNights: Number(PUBLIC_BOOKING_MAX_NIGHTS),
	minNights: Number(PUBLIC_BOOKING_MIN_NIGHTS)
} as const;

export const BOOKING_STATUS = {
	CONFIRMED: 'confirmed',
	CANCELLED: 'cancelled',
	PENDING: 'pending'
} as const;
